//---------------------------------------------------------------------------------------
// Master instance constructor
//---------------------------------------------------------------------------------------

()

  [
  @test?: false

  Debug.println("Member: Master.!() - Mind instance constructor called.")

  // Call default starting point when engine runtime is present - i.e. not in IDE
  on_startup when Debug.engine_present?
  ]

